<?xml version="1.0"?>
<robot name="trike" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Parameters -->
  <xacro:property name="wheel_radius" value="0.24"/>  <!-- 19-inch diameter -->
  <xacro:property name="wheel_width" value="0.076"/>  <!-- 3-inch width -->
  <xacro:property name="frame_length" value="2.44"/>  <!-- 8 feet -->
  <xacro:property name="frame_width" value="0.61"/>  <!-- 2 feet -->
  <xacro:property name="wheelbase" value="1.22"/>  <!-- 4 feet -->
  <xacro:property name="steering_angle_max" value="0.96"/>  <!-- 55 degrees in radians -->

  <!-- Base link (reference point) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.5 0.3 0.1"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
  </link>

  <!-- rear wheel -->
  <link name="rear_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
  </link>
  <joint name="rear_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_wheel"/>
    <origin xyz="0 0 -${wheel_radius}"/>
  </joint>

    <!-- Front Frame (Extending to Steering) -->
  <link name="front_frame">
    <visual>
      <geometry>
        <box size="${frame_length} 0.1 0.1"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0"/>
      </material>
    </visual>
  </link>
  <joint name="frame_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_frame"/>
    <origin xyz="${wheelbase} 0 0"/>
  </joint>
  
  <!-- Steering Mechanism -->
  <link name="steering_bar"/>
  <joint name="steering_joint" type="revolute">
    <parent link="front_frame"/>
    <child link="steering_bar"/>
    <origin xyz="${wheelbase} 0 0.1"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${steering_angle_max}" upper="${steering_angle_max}" effort="1.0" velocity="1.0"/>
  </joint>
  
  <!-- Front Wheels -->
  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
  </link>
  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
  </link>
  
  <!-- Front Wheel Joints (Connected to Steering Bar) -->
  <joint name="front_left_wheel_joint" type="revolute">
    <parent link="steering_bar"/>
    <child link="front_left_wheel"/>
    <origin xyz="${wheelbase} ${frame_width / 2} -${wheel_radius}"/>
    <axis xyz="0 1 0"/>
    <limit effort="10.0" lower="-1.57" upper="1.57" velocity="1.0"/>
  </joint>
  
  <joint name="front_right_wheel_joint" type="revolute">
    <parent link="steering_bar"/>
    <child link="front_right_wheel"/>
    <origin xyz="${wheelbase} -${frame_width / 2} -${wheel_radius}"/>
    <axis xyz="0 1 0"/>
    <limit effort="10.0" lower="-1.57" upper="1.57" velocity="1.0"/>
  </joint>

</robot>